[versions]
minestom = "2026.07.22-26.2"
adventure = "5.2.0"
slf4j = "2.0.18"
jetbrainsAnnotations = "26.1.0"
gson = "2.14.0"

[libraries]
minestom = { module = "net.minestom:minestom", version.ref = "minestom" }
logging-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
jetbrainsAnnotations = { module = "org.jetbrains:annotations", version.ref = "jetbrainsAnnotations" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }
adventure = { module = "net.kyori:adventure-api", version.ref = "adventure" }
adventure-nbt = { module = "net.kyori:adventure-nbt", version.ref = "adventure" }
